meta_product_name: "Le Wagon Simulator"
meta_title: "Le Wagon Simulator - Relive your Le Wagon experience through a game"
meta_description: "A simple game"
meta_image: "stress.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
