import "bootstrap";
import Typed from 'typed.js';
import { initSortable } from '../plugins/init_sortable';
import { incrementStress } from '../plugins/init_increment';
import { incrementScore } from '../plugins/init_increment';

const typedInHome = document.querySelector("#typed");

if (typedInHome) {
  var options = {
    stringsElement: '#typed-strings',
    typeSpeed: 40,
    loop: true,
    loopCount: Infinity,
  };


  var typed = new Typed('#typed', options);
}


incrementStress();
incrementScore();
initSortable();




/* ----------------------------------------------
 * Generated by Animista on 2019-11-27 16:53:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
            transform: translateY(-100px);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
            transform: translateY(-100px);
  }
}
